### ISSUE TITLE
Issue with IncrementalSave (from Ctrl+S menu)

### ISSUE THREAD

**Issue by Yadovitiy** [bonjorno7/PowerSave#9]
Hi! I have a problem-when I try to make incremental save from ctrl+s menu,I get an error message:

Traceback (most recent call last):
  File "C:\Users\EUdod\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MACHIN3tools\ui\operators\save.py", line 67, in execute
    add_path_to_recent_files(save_path)
  File "C:\Users\EUdod\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MACHIN3tools\utils\system.py", line 20, in add_path_to_recent_files
    content = f.read()
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\python\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 183: character maps to <undefined>

location: <unknown location>:-1

If I press button powersave(hops)-it's works great. But it's not so comfortable as ctrl+s....

**Comment by bonjorno7** [comment]
I'm afraid I didn't make Machine3 Tools.
But I'll download it, try to fix the issue, and see if I can contact Machin3 about it.

**Comment by Yadovitiy** [comment]
Oops. I missed that this is a bug by machinetool -I was careless and thought saving issues had something to do with powersave. 
I really appreciate your help.
